name = "Purposeful Create Reloaded"
author = "Hess Lewis"
version = "v1.0.0-rc.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f9b0fc286da42d5f1be5e3280aa588006629193fcc55ff84047516e801249db"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.88"
