name = "Purposeful Create Reloaded"
author = "Hess Lewis"
version = "v1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb7c3ccb0983fc5da9542b22789036ea7b1a3f596ab8e403a8839202db674f8e"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.105"
