name = "Purposeful Create Reloaded"
author = "Hess Lewis"
version = "v1.0.0-rc.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a211cb7f8839c93126c8f7c0e9ca062434d494e6f7a3f76b57617c1129a5d379"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.88"
