name = "Purposeful Create Reloaded"
author = "Hess Lewis"
version = "v1.0.0-rc.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc83df9f3da039ff6f5b82bc9399b5a2983e6b8723bf2471703fa91fa06eb4b0"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.88"
