name = "Purposeful Create Reloaded"
author = "Hess Lewis"
version = "v1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98765026f719676183810869ad87c7ed6e7f03adc27d85c7668fc059d124ed1b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.88"
