name = "Purposeful Create Reloaded"
author = "Hess Lewis"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5e2e0f5d823a9230613dfccdeb51dc784e11485c22b12d1a4d701d2f0d6a925"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.88"
