name = "Purposeful Create Reloaded"
author = "Hess Lewis"
version = "v1.0.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "313991829dc21c9c1d66a7bd6d0b55a5564cfc9317161578cce2b5c5944eb00a"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.88"
