name = "Purposeful Create Reloaded"
author = "Hess Lewis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fca56ddc0769b8ab07594b9bd48a54d10e2b22657be6020a072c443eb66202c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.88"
