name = "Purposeful Create Reloaded"
author = "Hess Lewis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05dfd1374cab12ac1ff959d6726ec5813736dd5752edacd3ebd34a4a5bf1c82d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.88"
