name = "Purposeful Create Reloaded"
author = "Hess Lewis"
version = "v1.0.0-rc.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d269a42b33975196805513c99623505a52e5f2cca03f1da683dff125111f11f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.88"
